#!/usr/bin/env python3

import sys
import os

from firefox_bookmarks import merge_files


SCRIPT_NAME = os.path.basename(__file__)
USAGE = f"USAGE: {SCRIPT_NAME} [FROM].json [TO].json [OUT].json"

def run():
    try:
        from_fname, to_fname, out_fname = sys.argv[1:4]
    except:
        print(USAGE)
        return sys.exit(1)

    merge_files(from_fname, to_fname, out_fname)


if __name__ == "__main__":
    run()
